<?php
$typeArr[1] = '方案';
$typeArr[2] = '中小企业解决方案';
$typeArr[3] = '大型企业解决方案';
$typeArr[4] = '淘宝店铺解决方案';
$typeArr[5] = '天猫商城解决方案';
$typeArr[6] = '服务';
$typeArr[7] = '移动互联';
$typeArr[8] = '电商营销';
$typeArr[9] = '品牌网站建设';
$typeArr[11] = '网络推广';
$typeArr[12] = '增值服务';
$typeArr[13] = '案例';
$typeArr[15] = '电商营销';
$typeArr[16] = '移动互联类';
$typeArr[17] = '关于';
$typeArr[18] = '关于我们';
$typeArr[19] = '加入我们';
$typeArr[20] = '动态';
$typeArr[21] = '公司动态';
$typeArr[22] = '行业动态';
$typeArr[23] = '网站优化';
$typeArr[24] = '建站技术';
$typeArr[25] = '常见问题';
$typeArr[26] = '联系';
$typeArr[27] = '品牌网站建设';
?>