<div class="ue_grid_1 listbox newlist">
            <div class="sc_preview"><a target="_blank" href="[field:arcurl/]"><img src="[field:litpic/]" alt="[field:fulltitle/]" /></a>
            </div>
            <div class="sc_info">
              
              <div class="pdw20">
                <h3><a target="_blank" href="[field:arcurl/]">[field:title/]</a></h3>
			  </div>
              
              <div class="listline"></div>
              <div class="pdw20">
				<div class="bdsharebuttonbox fl"><a href="#" class="bds_more" data-cmd="more"></a><a href="#" class="bds_weixin" data-cmd="weixin" title="分享到微信"></a><a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a></div>
<script>window._bd_share_config={"common":{"bdSnsKey":{},"bdText":"","bdMini":"2","bdMiniList":false,"bdPic":"","bdStyle":"2","bdSize":"16"},"share":{}};with(document)0[(getElementsByTagName('head')[0]||body).appendChild(createElement('script')).src='http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion='+~(-new Date()/36e5)];</script>

                <div class="artfields fl listfields">
                  <ul>
					  <li class="likeit"><a href="javascript:viod(0)">[field:click/]</a></li>
                  </ul>
                </div>

                <div class="medal fr">
                    <div class="colorplates colorsmall mb20">
                <ul>
			                  <li class="black"><a href="javascript:viod(0)"></a></li>
			                  <li class="blue"><a href="javascript:viod(0)"></a></li>
			                  
                </ul>
                  </div>
				</div>
                <div class="clear"></div>
              </div>
              <div class="clear"></div>
            </div>
          </div>