<?php
$z[0]=Array("pagestyle","",0,86);
$z[0][4]['maxwidth']="0";
$z[0][4]['pagepicnum']="0";
$z[0][4]['ddmaxwidth']="0";
$z[0][4]['row']="0";
$z[0][4]['col']="0";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/150223/co150223125113-0.jpg ",88,239);
$z[1][4]['ddimg']="/uploads/allimg/150223/co150223125113-0.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="750";
$z[1][4]['height']="487";
$z[2]=Array("img"," /uploads/allimg/150223/co150223125113-1.jpg ",241,392);
$z[2][4]['ddimg']="/uploads/allimg/150223/co150223125113-1.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="750";
$z[2][4]['height']="634";
$z[3]=Array("img"," /uploads/allimg/150223/co150223125113-2.jpg ",394,545);
$z[3][4]['ddimg']="/uploads/allimg/150223/co150223125113-2.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="750";
$z[3][4]['height']="634";

?>