<?php
$z[0]=Array("pagestyle","",0,81);
$z[0][4]['maxwidth']="";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="";
$z[0][4]['row']="";
$z[0][4]['col']="";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/150223/co150223124Q7-0.png ",83,234);
$z[1][4]['ddimg']="/uploads/allimg/150223/co150223124Q7-0.png";
$z[1][4]['text']="";
$z[1][4]['width']="1903";
$z[1][4]['height']="4409";
$z[2]=Array("img"," /uploads/allimg/150223/co150223124Q7-1.png ",236,387);
$z[2][4]['ddimg']="/uploads/allimg/150223/co150223124Q7-1.png";
$z[2][4]['text']="";
$z[2][4]['width']="1903";
$z[2][4]['height']="2391";
$z[3]=Array("img"," /uploads/allimg/150223/co150223124Q7-2.png ",389,540);
$z[3][4]['ddimg']="/uploads/allimg/150223/co150223124Q7-2.png";
$z[3][4]['text']="";
$z[3][4]['width']="1903";
$z[3][4]['height']="1540";

?>