<?php
$z[0]=Array("field","",13,41);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",50,76);
$z[1][4]['name']="currentstyle";
$z[2]=Array("field","",114,137);
$z[2][4]['name']="seotitle";
$z[3]=Array("field","",155,184);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n                			<li><a href=\"[field:typelink/]\" target=\"_self\">[field:typename/]</a></li>\r\n                		",207,374);
$z[4][4]['type']="son";
$z[4][4]['noself']="yes";

?>