<?php
$z[0]=Array("pagestyle","",0,86);
$z[0][4]['maxwidth']="0";
$z[0][4]['pagepicnum']="0";
$z[0][4]['ddmaxwidth']="0";
$z[0][4]['row']="0";
$z[0][4]['col']="0";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/150223/co150223125108-0.png ",88,241);
$z[1][4]['ddimg']="/uploads/allimg/150223/co150223125108-0.png";
$z[1][4]['text']="";
$z[1][4]['width']="1903";
$z[1][4]['height']="2434";
$z[2]=Array("img"," /uploads/allimg/150223/co150223125108-1.png ",243,395);
$z[2][4]['ddimg']="/uploads/allimg/150223/co150223125108-1.png";
$z[2][4]['text']="";
$z[2][4]['width']="1903";
$z[2][4]['height']="954";

?>