<?php
$z[0]=Array("pagestyle","",0,86);
$z[0][4]['maxwidth']="0";
$z[0][4]['pagepicnum']="0";
$z[0][4]['ddmaxwidth']="0";
$z[0][4]['row']="0";
$z[0][4]['col']="0";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/150223/co150223124U2-0.jpg ",88,238);
$z[1][4]['ddimg']="/uploads/allimg/150223/co150223124U2-0.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="750";
$z[1][4]['height']="1041";
$z[2]=Array("img"," /uploads/allimg/150223/co150223124U2-1.jpg ",240,389);
$z[2][4]['ddimg']="/uploads/allimg/150223/co150223124U2-1.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="750";
$z[2][4]['height']="581";
$z[3]=Array("img"," /uploads/allimg/150223/co150223124U2-2.jpg ",391,540);
$z[3][4]['ddimg']="/uploads/allimg/150223/co150223124U2-2.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="750";
$z[3][4]['height']="586";
$z[4]=Array("img"," /uploads/allimg/150223/co150223124U2-3.jpg ",542,691);
$z[4][4]['ddimg']="/uploads/allimg/150223/co150223124U2-3.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="750";
$z[4][4]['height']="586";

?>