<?php
$z[0]=Array("field","",335,354);
$z[0][4]['name']="title";
$z[1]=Array("global","",355,381);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",422,444);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",484,535);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1351,1387);
$z[4][4]['filename']="head2.htm";
$z[5]=Array("field","",1442,1461);
$z[5][4]['name']="title";
$z[6]=Array("field","",1514,1532);
$z[6][4]['name']="body";
$z[7]=Array("type","[field:typeurl/]",2326,2376);
$z[7][4]['typeid']="6";
$z[8]=Array("arclist","\r\n      <li><span></span><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n      ",2588,2720);
$z[8][4]['row']="10";
$z[8][4]['orderby']="click";
$z[9]=Array("include","",2875,2912);
$z[9][4]['filename']="footer.htm";

?>