<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",16,170);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",186,201);
$z[2]=Array("title","",217,231);
$z[3]=Array("pubdate","",290,336);
$z[3][4]['function']="GetDateTimeMK(@me)";
$z[4]=Array("click","",365,379);
$z[5]=Array("scores","",408,423);
$z[6]=Array("description","",469,489);

?>