{dede:pagestyle maxwidth='0' pagepicnum='0' ddmaxwidth='0' row='0' col='0' value='1'/}
{dede:img ddimg='/uploads/allimg/150223/co150223124Q7-0.png' text='' width='1903' height='4409'} /uploads/allimg/150223/co150223124Q7-0.png {/dede:img}
{dede:img ddimg='/uploads/allimg/150223/co150223124Q7-1.png' text='' width='1903' height='2391'} /uploads/allimg/150223/co150223124Q7-1.png {/dede:img}
{dede:img ddimg='/uploads/allimg/150223/co150223124Q7-2.png' text='' width='1903' height='1540'} /uploads/allimg/150223/co150223124Q7-2.png {/dede:img}
