<?php
$z[0]=Array("pagestyle","",0,86);
$z[0][4]['maxwidth']="0";
$z[0][4]['pagepicnum']="0";
$z[0][4]['ddmaxwidth']="0";
$z[0][4]['row']="0";
$z[0][4]['col']="0";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/150223/co150223124Q7-0.png ",88,239);
$z[1][4]['ddimg']="/uploads/allimg/150223/co150223124Q7-0.png";
$z[1][4]['text']="";
$z[1][4]['width']="1903";
$z[1][4]['height']="4409";
$z[2]=Array("img"," /uploads/allimg/150223/co150223124Q7-1.png ",241,392);
$z[2][4]['ddimg']="/uploads/allimg/150223/co150223124Q7-1.png";
$z[2][4]['text']="";
$z[2][4]['width']="1903";
$z[2][4]['height']="2391";
$z[3]=Array("img"," /uploads/allimg/150223/co150223124Q7-2.png ",394,545);
$z[3][4]['ddimg']="/uploads/allimg/150223/co150223124Q7-2.png";
$z[3][4]['text']="";
$z[3][4]['width']="1903";
$z[3][4]['height']="1540";

?>