<?php
$z[0]=Array("pagestyle","",0,81);
$z[0][4]['maxwidth']="";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="";
$z[0][4]['row']="";
$z[0][4]['col']="";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/150223/co150223124924-0.png ",83,236);
$z[1][4]['ddimg']="/uploads/allimg/150223/co150223124924-0.png";
$z[1][4]['text']="";
$z[1][4]['width']="1903";
$z[1][4]['height']="1937";
$z[2]=Array("img"," /uploads/allimg/150223/co150223124924-1.png ",238,391);
$z[2][4]['ddimg']="/uploads/allimg/150223/co150223124924-1.png";
$z[2][4]['text']="";
$z[2][4]['width']="1903";
$z[2][4]['height']="2762";
$z[3]=Array("img"," /uploads/allimg/150223/co150223124924-2.png ",393,546);
$z[3][4]['ddimg']="/uploads/allimg/150223/co150223124924-2.png";
$z[3][4]['text']="";
$z[3][4]['width']="1903";
$z[3][4]['height']="3764";
$z[4]=Array("img"," /uploads/allimg/150223/co150223124924-3.png ",548,701);
$z[4][4]['ddimg']="/uploads/allimg/150223/co150223124924-3.png";
$z[4][4]['text']="";
$z[4][4]['width']="1903";
$z[4][4]['height']="3021";

?>