<?php
$z[0]=Array("pagestyle","",0,81);
$z[0][4]['maxwidth']="";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="";
$z[0][4]['row']="";
$z[0][4]['col']="";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/150223/co150223124U2-0.jpg ",83,233);
$z[1][4]['ddimg']="/uploads/allimg/150223/co150223124U2-0.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="750";
$z[1][4]['height']="1041";
$z[2]=Array("img"," /uploads/allimg/150223/co150223124U2-1.jpg ",235,384);
$z[2][4]['ddimg']="/uploads/allimg/150223/co150223124U2-1.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="750";
$z[2][4]['height']="581";
$z[3]=Array("img"," /uploads/allimg/150223/co150223124U2-2.jpg ",386,535);
$z[3][4]['ddimg']="/uploads/allimg/150223/co150223124U2-2.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="750";
$z[3][4]['height']="586";
$z[4]=Array("img"," /uploads/allimg/150223/co150223124U2-3.jpg ",537,686);
$z[4][4]['ddimg']="/uploads/allimg/150223/co150223124U2-3.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="750";
$z[4][4]['height']="586";

?>