<?php
$z[0]=Array("pagestyle","",0,86);
$z[0][4]['maxwidth']="0";
$z[0][4]['pagepicnum']="0";
$z[0][4]['ddmaxwidth']="0";
$z[0][4]['row']="0";
$z[0][4]['col']="0";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/150223/co150223124U7-0.jpg ",88,238);
$z[1][4]['ddimg']="/uploads/allimg/150223/co150223124U7-0.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="970";
$z[1][4]['height']="1168";
$z[2]=Array("img"," /uploads/allimg/150223/co150223124U7-1.jpg ",240,389);
$z[2][4]['ddimg']="/uploads/allimg/150223/co150223124U7-1.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="970";
$z[2][4]['height']="961";

?>