<li>
        <div onClick="location.href='[field:arcurl/]';" class="pic"><img src="[field:litpic/]">
          <div class="picFc" style="opacity: 0; display: block;"></div>
        </div>
        <div class="txt">
          <h3><a href="[field:arcurl/]">[field:title/]</a></h3>
          <p>[field:description function="cn_substr(@me,100)"/]... </p></div>
        <div class="newsDate"><span class="d1">[field:pubdate function="MyDate('d',@me)"/]</span><span class="d2">[field:pubdate function="MyDate('F',@me)"/]<br>[field:pubdate function="MyDate('Y',@me)"/]</span></div>
      </li>