<?php
$z[0]=Array("arcurl","",43,58);
$z[1]=Array("litpic","",84,99);
$z[2]=Array("arcurl","",242,257);
$z[3]=Array("title","",259,273);
$z[4]=Array("description","",297,347);
$z[4][4]['function']="cn_substr(@me,100)";
$z[5]=Array("pubdate","",410,453);
$z[5][4]['function']="MyDate('d',@me)";
$z[6]=Array("pubdate","",477,520);
$z[6][4]['function']="MyDate('F',@me)";
$z[7]=Array("pubdate","",524,567);
$z[7][4]['function']="MyDate('Y',@me)";

?>