<?php
$z[0]=Array("global","",303,325);
$z[0][4]['name']="address";
$z[1]=Array("global","",475,493);
$z[1][4]['name']="tel";
$z[2]=Array("type","<li><a href=\"[field:typeurl/]\" class=\"googleplus\"><i class=\"icon-mobile\"></i><span>[field:typename/]</span></a></li>",648,798);
$z[2][4]['typeid']="7";
$z[3]=Array("type","<li><a href=\"[field:typeurl/]\" class=\"dribbble\"><i class=\"icon-cart\"></i><span>[field:typename/]</span></a></li>",810,956);
$z[3][4]['typeid']="8";
$z[4]=Array("type","<li><a href=\"[field:typeurl/]\" class=\"twitter\"><i class=\"icon-html5\"></i><span>[field:typename/]</span></a></li>",968,1114);
$z[4][4]['typeid']="9";
$z[5]=Array("type","<li><a href=\"[field:typeurl/]\" class=\"facebook\"><i class=\"icon-globe\"></i><span>[field:typename/]</span></a></li>",1126,1274);
$z[5][4]['typeid']="11";
$z[6]=Array("type","<li><a href=\"[field:typeurl/]\" class=\"linkedin\"><i class=\"icon-calculate\"></i><span>[field:typename/]</span></a></li>",1286,1438);
$z[6][4]['typeid']="12";
$z[7]=Array("field","(@me=='')? @me='active-page':@me='';",1822,1908);
$z[7][4]['name']="typeid";
$z[7][4]['runphp']="yes";
$z[8]=Array("channelartlist","                \r\n				<li><a href=\"{dede:field name='typeurl'/}\" class=\"{dede:field.currentstyle/}\" ><span aria-hidden=\"true\" class=\"li_{dede:field.seotitle /} nav_icon\"></span>{dede:field name='typename'/}</a>\r\n					<ul>\r\n						{dede:channel type='son' noself='yes'}\r\n                			<li><a href=\"[field:typelink/]\" target=\"_self\">[field:typename/]</a></li>\r\n                		{/dede:channel}\r\n					</ul>\r\n				</li>                                \r\n                ",2001,2553);
$z[8][4]['typeid']="top";
$z[8][4]['currentstyle']="active-page";
$z[9]=Array("field","",2838,2860);
$z[9][4]['name']="typename";
$z[10]=Array("field","",2906,2935);
$z[10][4]['name']="position";
$z[11]=Array("global","",3100,3125);
$z[11][4]['name']="cfg_cmsurl";
$z[12]=Array("channel","      \r\n         <li><a class=\"tooltip\" data-categories=\"animation\" href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n      ",3575,3871);
$z[12][4]['type']="son";
$z[12][4]['currentstyle']="<li><a class='tooltip active' data-categories='animation' href='~typelink~'>~typename~</a></li>";

?>