<?php
$z[0]=Array("global","",312,334);
$z[0][4]['name']="address";
$z[1]=Array("global","",487,505);
$z[1][4]['name']="tel";
$z[2]=Array("type","\r\n            <li><a href=\"[field:typeurl/]\" class=\"googleplus\"><i class=\"icon-mobile\"></i><span>[field:typename/]</span></a></li>\r\n            ",670,848);
$z[2][4]['typeid']="7";
$z[3]=Array("type","\r\n            <li><a href=\"[field:typeurl/]\" class=\"dribbble\"><i class=\"icon-cart\"></i><span>[field:typename/]</span></a></li>\r\n            ",862,1036);
$z[3][4]['typeid']="8";
$z[4]=Array("type","\r\n            <li><a href=\"[field:typeurl/]\" class=\"twitter\"><i class=\"icon-html5\"></i><span>[field:typename/]</span></a></li>\r\n            ",1050,1224);
$z[4][4]['typeid']="9";
$z[5]=Array("type","\r\n            <li><a href=\"[field:typeurl/]\" class=\"facebook\"><i class=\"icon-globe\"></i><span>[field:typename/]</span></a></li>\r\n            ",1238,1414);
$z[5][4]['typeid']="11";
$z[6]=Array("type","\r\n            <li><a href=\"[field:typeurl/]\" class=\"linkedin\"><i class=\"icon-calculate\"></i><span>[field:typename/]</span></a></li>\r\n            ",1428,1608);
$z[6][4]['typeid']="12";
$z[7]=Array("field","(@me=='')? @me='active-page':@me='';",1986,2072);
$z[7][4]['name']="typeid";
$z[7][4]['runphp']="yes";
$z[8]=Array("channelartlist","\r\n              <li><a href=\"{dede:field name='typeurl'/}\" class=\"{dede:field.currentstyle/}\" ><span aria-hidden=\"true\" class=\"li_{dede:field.seotitle /} nav_icon\"></span>{dede:field name='typename'/}</a>\r\n                <ul>\r\n                  {dede:channel type='son' noself='yes'}\r\n                  <li><a href=\"[field:typelink/]\" target=\"_self\">[field:typename/]</a></li>\r\n                  {/dede:channel}\r\n                </ul>\r\n              </li>\r\n              ",2163,2718);
$z[8][4]['typeid']="top";
$z[8][4]['currentstyle']="active-page";

?>