<?php
$z[0]=Array("field","",331,350);
$z[0][4]['name']="title";
$z[1]=Array("global","",351,377);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",418,447);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",487,545);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1344,1380);
$z[4][4]['filename']="head2.htm";
$z[5]=Array("type","[field:typeurl /]",3107,3158);
$z[5][4]['typeid']="8";
$z[6]=Array("type","[field:typeurl /]",3907,3958);
$z[6][4]['typeid']="8";
$z[7]=Array("type","[field:typeurl /]",4682,4733);
$z[7][4]['typeid']="8";
$z[8]=Array("type","[field:typeurl /]",5383,5434);
$z[8][4]['typeid']="8";
$z[9]=Array("include","",5829,5866);
$z[9][4]['filename']="footer.htm";

?>