<?php
$z[0]=Array("field","",333,352);
$z[0][4]['name']="title";
$z[1]=Array("global","",353,379);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",420,449);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",489,547);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1361,1397);
$z[4][4]['filename']="head2.htm";
$z[5]=Array("type","[field:typeurl /]",3497,3548);
$z[5][4]['typeid']="9";
$z[6]=Array("type","[field:typeurl /]",4250,4302);
$z[6][4]['typeid']="11";
$z[7]=Array("type","[field:typeurl /]",4887,4939);
$z[7][4]['typeid']="11";
$z[8]=Array("type","[field:typeurl /]",5758,5809);
$z[8][4]['typeid']="7";
$z[9]=Array("type","[field:typeurl /]",6302,6353);
$z[9][4]['typeid']="7";
$z[10]=Array("type","[field:typeurl /]",7171,7223);
$z[10][4]['typeid']="12";
$z[11]=Array("type","[field:typeurl /]",7935,7987);
$z[11][4]['typeid']="12";
$z[12]=Array("type","[field:typeurl /]",8748,8800);
$z[12][4]['typeid']="12";
$z[13]=Array("include","",9192,9229);
$z[13][4]['filename']="footer.htm";

?>