<?php
$z[0]=Array("field","",332,351);
$z[0][4]['name']="title";
$z[1]=Array("global","",352,378);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",419,448);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",488,546);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1350,1386);
$z[4][4]['filename']="head2.htm";
$z[5]=Array("global","",13203,13220);
$z[5][4]['name']="qq";
$z[6]=Array("include","",13455,13492);
$z[6][4]['filename']="footer.htm";

?>