<?php
$z[0]=Array("field","",331,350);
$z[0][4]['name']="title";
$z[1]=Array("global","",351,377);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",418,447);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",487,545);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1415,1451);
$z[4][4]['filename']="head2.htm";
$z[5]=Array("global","",27157,27174);
$z[5][4]['name']="qq";
$z[6]=Array("include","",27409,27446);
$z[6][4]['filename']="footer.htm";

?>