<?php
$z[0]=Array("field","",332,351);
$z[0][4]['name']="title";
$z[1]=Array("global","",352,378);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",419,448);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",488,546);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1352,1388);
$z[4][4]['filename']="head2.htm";
$z[5]=Array("type","[field:typeurl /]",3115,3166);
$z[5][4]['typeid']="8";
$z[6]=Array("type","[field:typeurl /]",3915,3966);
$z[6][4]['typeid']="8";
$z[7]=Array("type","[field:typeurl /]",4690,4741);
$z[7][4]['typeid']="8";
$z[8]=Array("type","[field:typeurl /]",5391,5442);
$z[8][4]['typeid']="8";
$z[9]=Array("include","",5837,5874);
$z[9][4]['filename']="footer.htm";

?>