<?php
$z[0]=Array("field","",331,350);
$z[0][4]['name']="title";
$z[1]=Array("global","",351,377);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",418,447);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",487,545);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1345,1381);
$z[4][4]['filename']="head2.htm";
$z[5]=Array("type","[field:typeurl /]",2765,2816);
$z[5][4]['typeid']="8";
$z[6]=Array("type","[field:typeurl /]",3565,3616);
$z[6][4]['typeid']="8";
$z[7]=Array("type","[field:typeurl /]",4340,4391);
$z[7][4]['typeid']="8";
$z[8]=Array("type","[field:typeurl /]",5043,5094);
$z[8][4]['typeid']="8";
$z[9]=Array("type","[field:typeurl /]",5744,5795);
$z[9][4]['typeid']="8";
$z[10]=Array("type","[field:typeurl /]",6466,6517);
$z[10][4]['typeid']="8";
$z[11]=Array("include","",6907,6944);
$z[11][4]['filename']="footer.htm";

?>