<?php
$z[0]=Array("field","",332,351);
$z[0][4]['name']="title";
$z[1]=Array("global","",352,378);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",419,448);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",488,546);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1353,1389);
$z[4][4]['filename']="head2.htm";
$z[5]=Array("type","[field:typeurl /]",3489,3540);
$z[5][4]['typeid']="9";
$z[6]=Array("type","[field:typeurl /]",4242,4294);
$z[6][4]['typeid']="11";
$z[7]=Array("type","[field:typeurl /]",4879,4931);
$z[7][4]['typeid']="11";
$z[8]=Array("type","[field:typeurl /]",5750,5801);
$z[8][4]['typeid']="7";
$z[9]=Array("type","[field:typeurl /]",6294,6345);
$z[9][4]['typeid']="7";
$z[10]=Array("type","[field:typeurl /]",7163,7215);
$z[10][4]['typeid']="12";
$z[11]=Array("type","[field:typeurl /]",7927,7979);
$z[11][4]['typeid']="12";
$z[12]=Array("type","[field:typeurl /]",8740,8792);
$z[12][4]['typeid']="12";
$z[13]=Array("include","",9184,9221);
$z[13][4]['filename']="footer.htm";

?>