<?php
$z[0]=Array("field","",332,351);
$z[0][4]['name']="title";
$z[1]=Array("global","",352,378);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",419,448);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",488,546);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1352,1388);
$z[4][4]['filename']="head2.htm";
$z[5]=Array("type","[field:typeurl /]",2912,2963);
$z[5][4]['typeid']="9";
$z[6]=Array("type","[field:typeurl /]",3665,3716);
$z[6][4]['typeid']="9";
$z[7]=Array("type","[field:typeurl /]",4301,4353);
$z[7][4]['typeid']="11";
$z[8]=Array("type","[field:typeurl /]",5172,5224);
$z[8][4]['typeid']="11";
$z[9]=Array("type","[field:typeurl /]",5715,5767);
$z[9][4]['typeid']="11";
$z[10]=Array("type","[field:typeurl /]",6585,6637);
$z[10][4]['typeid']="12";
$z[11]=Array("type","[field:typeurl /]",7349,7401);
$z[11][4]['typeid']="12";
$z[12]=Array("type","[field:typeurl /]",8162,8214);
$z[12][4]['typeid']="12";
$z[13]=Array("type","[field:typeurl /]",8851,8903);
$z[13][4]['typeid']="11";
$z[14]=Array("include","",9301,9338);
$z[14][4]['filename']="footer.htm";

?>