<?php
$z[0]=Array("field","",333,352);
$z[0][4]['name']="title";
$z[1]=Array("global","",353,379);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",420,449);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",489,547);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1360,1396);
$z[4][4]['filename']="head2.htm";
$z[5]=Array("type","[field:typeurl /]",3123,3174);
$z[5][4]['typeid']="8";
$z[6]=Array("type","[field:typeurl /]",3923,3974);
$z[6][4]['typeid']="8";
$z[7]=Array("type","[field:typeurl /]",4698,4749);
$z[7][4]['typeid']="8";
$z[8]=Array("type","[field:typeurl /]",5399,5450);
$z[8][4]['typeid']="8";
$z[9]=Array("include","",5845,5882);
$z[9][4]['filename']="footer.htm";

?>