<?php
$z[0]=Array("field","",333,352);
$z[0][4]['name']="title";
$z[1]=Array("global","",353,379);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",420,449);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",489,547);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1360,1396);
$z[4][4]['filename']="head2.htm";
$z[5]=Array("type","[field:typeurl /]",2920,2971);
$z[5][4]['typeid']="9";
$z[6]=Array("type","[field:typeurl /]",3673,3724);
$z[6][4]['typeid']="9";
$z[7]=Array("type","[field:typeurl /]",4309,4361);
$z[7][4]['typeid']="11";
$z[8]=Array("type","[field:typeurl /]",5180,5232);
$z[8][4]['typeid']="11";
$z[9]=Array("type","[field:typeurl /]",5723,5775);
$z[9][4]['typeid']="11";
$z[10]=Array("type","[field:typeurl /]",6593,6645);
$z[10][4]['typeid']="12";
$z[11]=Array("type","[field:typeurl /]",7357,7409);
$z[11][4]['typeid']="12";
$z[12]=Array("type","[field:typeurl /]",8170,8222);
$z[12][4]['typeid']="12";
$z[13]=Array("type","[field:typeurl /]",8859,8911);
$z[13][4]['typeid']="11";
$z[14]=Array("include","",9309,9346);
$z[14][4]['filename']="footer.htm";

?>