<?php
$z[0]=Array("field","",334,353);
$z[0][4]['name']="title";
$z[1]=Array("global","",354,380);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",421,450);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",490,548);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1379,1415);
$z[4][4]['filename']="head2.htm";
$z[5]=Array("global","",3296,3313);
$z[5][4]['name']="qq";
$z[6]=Array("include","",3577,3614);
$z[6][4]['filename']="footer.htm";

?>