<?php
$z[0]=Array("field","",332,351);
$z[0][4]['name']="title";
$z[1]=Array("global","",352,378);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",419,448);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",488,546);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1353,1389);
$z[4][4]['filename']="head2.htm";
$z[5]=Array("type","[field:typeurl /]",2773,2824);
$z[5][4]['typeid']="8";
$z[6]=Array("type","[field:typeurl /]",3573,3624);
$z[6][4]['typeid']="8";
$z[7]=Array("type","[field:typeurl /]",4348,4399);
$z[7][4]['typeid']="8";
$z[8]=Array("type","[field:typeurl /]",5051,5102);
$z[8][4]['typeid']="8";
$z[9]=Array("type","[field:typeurl /]",5752,5803);
$z[9][4]['typeid']="8";
$z[10]=Array("type","[field:typeurl /]",6474,6525);
$z[10][4]['typeid']="8";
$z[11]=Array("include","",6915,6952);
$z[11][4]['filename']="footer.htm";

?>