<?php
$z[0]=Array("field","",331,350);
$z[0][4]['name']="title";
$z[1]=Array("global","",351,377);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",418,447);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",487,545);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1344,1380);
$z[4][4]['filename']="head2.htm";
$z[5]=Array("type","[field:typeurl /]",2904,2955);
$z[5][4]['typeid']="9";
$z[6]=Array("type","[field:typeurl /]",3657,3708);
$z[6][4]['typeid']="9";
$z[7]=Array("type","[field:typeurl /]",4293,4345);
$z[7][4]['typeid']="11";
$z[8]=Array("type","[field:typeurl /]",5164,5216);
$z[8][4]['typeid']="11";
$z[9]=Array("type","[field:typeurl /]",5707,5759);
$z[9][4]['typeid']="11";
$z[10]=Array("type","[field:typeurl /]",6577,6629);
$z[10][4]['typeid']="12";
$z[11]=Array("type","[field:typeurl /]",7341,7393);
$z[11][4]['typeid']="12";
$z[12]=Array("type","[field:typeurl /]",8154,8206);
$z[12][4]['typeid']="12";
$z[13]=Array("type","[field:typeurl /]",8843,8895);
$z[13][4]['typeid']="11";
$z[14]=Array("include","",9293,9330);
$z[14][4]['filename']="footer.htm";

?>