<?php
$z[0]=Array("field","",331,350);
$z[0][4]['name']="title";
$z[1]=Array("global","",351,377);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",418,447);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",487,545);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1345,1381);
$z[4][4]['filename']="head2.htm";
$z[5]=Array("type","[field:typeurl /]",3481,3532);
$z[5][4]['typeid']="9";
$z[6]=Array("type","[field:typeurl /]",4234,4286);
$z[6][4]['typeid']="11";
$z[7]=Array("type","[field:typeurl /]",4871,4923);
$z[7][4]['typeid']="11";
$z[8]=Array("type","[field:typeurl /]",5742,5793);
$z[8][4]['typeid']="7";
$z[9]=Array("type","[field:typeurl /]",6286,6337);
$z[9][4]['typeid']="7";
$z[10]=Array("type","[field:typeurl /]",7155,7207);
$z[10][4]['typeid']="12";
$z[11]=Array("type","[field:typeurl /]",7919,7971);
$z[11][4]['typeid']="12";
$z[12]=Array("type","[field:typeurl /]",8732,8784);
$z[12][4]['typeid']="12";
$z[13]=Array("include","",9176,9213);
$z[13][4]['filename']="footer.htm";

?>