<?php
$z[0]=Array("field","",335,354);
$z[0][4]['name']="title";
$z[1]=Array("global","",355,381);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",422,451);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",491,549);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1286,1322);
$z[4][4]['filename']="head2.htm";
$z[5]=Array("type","[field:typeurl/]",9513,9563);
$z[5][4]['typeid']="6";
$z[6]=Array("channel","\r\n                  <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n                  ",9784,9932);
$z[6][4]['type']="son";
$z[6][4]['typeid']="6";
$z[7]=Array("include","",10087,10124);
$z[7][4]['filename']="footer.htm";

?>