<?php
$z[0]=Array("field","",334,353);
$z[0][4]['name']="title";
$z[1]=Array("global","",354,380);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",421,450);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",490,548);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1279,1315);
$z[4][4]['filename']="head2.htm";
$z[5]=Array("type","[field:typeurl/]",9506,9556);
$z[5][4]['typeid']="6";
$z[6]=Array("channel","\r\n                  <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n                  ",9776,9924);
$z[6][4]['type']="son";
$z[6][4]['typeid']="6";
$z[7]=Array("include","",10079,10116);
$z[7][4]['filename']="footer.htm";

?>